version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
  steps:
    - checkout
    - setup_remote_docker:
        version: 17.05.0-ce
    - run: docker --version
      