version: 2
jobs:
  build:
    machine: true
      environment:
        http_proxy: lalala
        https_proxy: blablahblah
        no_proxy: boop
        AWS_DEFAULT_REGION: us-east-1
    steps:
        - checkout
        - run: echo "Hello world"